Repository umccr/icav2-cli-plugins, pull requests merged in 2023-12, with the labels that each got.

#243 Updated projectdata docstring to include copy subcommand
  src/plugins/subcommands/projectdata/__init__.py
Labels: documentation

#251 Autocompletion/add commands
  .github/workflows/update_autocompletion.yaml
  autocompletion/specs/icav2.yaml
Labels: enhancement

#254 Bugfix use tomllib over toml
  dev_scripts/bump_version.sh
  pyproject.toml
Labels: bug
